### ISSUE TITLE
problem to remove TAKO /BNB LP

### ISSUE THREAD

**Issue by Ebhitril** [TakoDeFi/takodefi-audits#1]
Hello, I was trying to remove liquidity in pancake, but I can't, liquidity does not appear, I had a TAKO / BNB LP farm and I followed the steps but pancake does not show me the liquidity to remove it

**Comment by TakoDeFi** [comment]
Hi! Have you tried importing the pool on PCS? if you can't resolve this problem please contact us on our TG https://t.me/TakoDefi

**Comment by Ebhitril** [comment]
> PCS

yes I try but I can´t see the token

**Comment by TakoDeFi** [comment]
Can you post a pic please?, and are you sure you unstaked your tokens from inactive farms?

**Comment by Ebhitril** [comment]
> Can you post a pic please?, and are you sure you unstaked your tokens from inactive farms?

ok 
![image](https://user-images.githubusercontent.com/82687691/115098272-6215d300-9eec-11eb-967d-3430bf0ce416.png)

![image](https://user-images.githubusercontent.com/82687691/115098289-778afd00-9eec-11eb-8a45-360181941eda.png)

![image](https://user-images.githubusercontent.com/82687691/115098305-99847f80-9eec-11eb-9c31-9027747b20da.png)

**Comment by TakoDeFi** [comment]
I see, can you go to Import pool here https://exchange.pancakeswap.finance/#/pool
And add a BNB/TAKO. Here is the TAKO address if you need it 0x2f3391aebe27393aba0a790aa5e1577fea0361c2

![Screenshot_20210416-220403](https://user-images.githubusercontent.com/79869294/115098768-d3ab4c80-9eff-11eb-8361-b1ccddfce58a.jpg)
![Screenshot_20210416-220414](https://user-images.githubusercontent.com/79869294/115098769-d443e300-9eff-11eb-934c-3935bf83b4da.jpg)

**Comment by Ebhitril** [comment]
i could, now i can buy at apeswap.
Thankyou very much
